### PR TITLE
Add outdated banner

### PR DESCRIPTION
**Pull request by shentao**

### CODE REVIEW

**Review by kazupon — APPROVED** [review]
Thanks!

**Comment by tnir** [comment]
This does not look deployed to `https://v1-jp.vuejs.org/` production. Why? @kazupon 
cc @shentao

**Comment by kazupon** [comment]
@tnir 
I'm sorry about this. I’m bad.
I’ll try to deploy it now.

**Comment by kazupon** [comment]
@tnir 
Done!
image

**Pull request merged**
